<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Acceptance Letter</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; color: #1f2937; font-size: 12px; line-height: 1.55; }
        .header { text-align: center; border-bottom: 3px solid #4338ca; padding-bottom: 16px; margin-bottom: 32px; }
        .brand { font-size: 24px; font-weight: 800; color: #4338ca; margin-bottom: 4px; }
        .title { font-size: 18px; font-weight: 700; margin-top: 24px; text-align: center; text-transform: uppercase; }
        .meta { width: 100%; margin: 24px 0; border-collapse: collapse; }
        .meta td { padding: 7px 8px; border-bottom: 1px solid #e5e7eb; vertical-align: top; }
        .meta td:first-child { width: 190px; color: #64748b; font-weight: 700; }
        .box { background: #f8fafc; border: 1px solid #e5e7eb; border-radius: 8px; padding: 14px; margin: 20px 0; }
        .signature { margin-top: 56px; width: 260px; margin-left: auto; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <div class="brand">NexaCampus</div>
        <div>Admission Office</div>
    </div>

    <div class="title">Acceptance Letter</div>

    <p>Dear <strong>{{ $application->full_name }}</strong>,</p>

    <p>
        Congratulations. Based on the admission review and selection process, you have been accepted as a prospective
        student at NexaCampus for the following program.
    </p>

    <table class="meta">
        <tr><td>Application Number</td><td>{{ $application->application_number }}</td></tr>
        <tr><td>Admission Period</td><td>{{ $application->period?->name ?? '-' }}</td></tr>
        <tr><td>Academic Year</td><td>{{ $application->period?->academicYear?->name ?? $application->period?->academic_year ?? '-' }}</td></tr>
        <tr><td>Study Program</td><td>{{ $application->studyProgram?->name ?? '-' }}</td></tr>
        <tr><td>Class Type</td><td>{{ ucfirst($application->class_type ?? '-') }}</td></tr>
        <tr><td>Final Score</td><td>{{ $application->final_score ?? '-' }}</td></tr>
        @if($studentProfile)
            <tr><td>NIM</td><td>{{ $studentProfile->nim }}</td></tr>
        @endif
    </table>

    <div class="box">
        This letter is generated by NexaCampus on {{ $generatedAt->format('d F Y H:i') }} and may be used for
        registration completion and onboarding purposes.
    </div>

    <p>
        Please follow further instructions from the admission office regarding student account activation and initial
        academic registration.
    </p>

    <div class="signature">
        <div>{{ $generatedAt->format('d F Y') }}</div>
        <br><br><br>
        <strong>Admission Office</strong>
    </div>
</body>
</html>
