<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #111827; }
        h1 { margin: 0 0 4px; font-size: 20px; }
        .meta { color: #6b7280; margin-bottom: 18px; }
        table { width: 100%; border-collapse: collapse; }
        th { background: #31235f; color: #fff; text-align: left; padding: 8px; }
        td { border-bottom: 1px solid #e5e7eb; padding: 8px; }
        .text-end { text-align: right; }
    </style>
</head>
<body>
    <h1>Financial Summary</h1>
    <div class="meta">
        Generated by {{ $meta['generated_by'] ?? '-' }} at {{ $meta['generated_at'] ?? now()->format('d M Y H:i') }}
    </div>

    <table>
        <thead>
            <tr>
                <th>Invoice Type</th>
                <th class="text-end">Invoices</th>
                <th class="text-end">Total</th>
                <th class="text-end">Paid</th>
                <th class="text-end">Outstanding</th>
            </tr>
        </thead>
        <tbody>
            @forelse($rows as $row)
                <tr>
                    <td>{{ $row['invoice_type'] }}</td>
                    <td class="text-end">{{ number_format($row['invoice_count']) }}</td>
                    <td class="text-end">Rp {{ number_format($row['total_amount'], 0, ',', '.') }}</td>
                    <td class="text-end">Rp {{ number_format($row['paid_amount'], 0, ',', '.') }}</td>
                    <td class="text-end">Rp {{ number_format($row['outstanding_amount'], 0, ',', '.') }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="5">No report data available.</td>
                </tr>
            @endforelse
        </tbody>
    </table>
</body>
</html>
