<!doctype html>
<html lang="id">
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #1f2937; }
        h1 { font-size: 20px; margin: 0 0 4px; }
        .muted { color: #6b7280; }
        .summary { width: 100%; margin: 18px 0; border-collapse: collapse; }
        .summary td { border: 1px solid #e5e7eb; padding: 7px; }
        .summary strong { display: block; font-size: 14px; color: #111827; }
        table.detail { width: 100%; border-collapse: collapse; }
        table.detail th { background: #f3f4f6; border: 1px solid #d1d5db; padding: 6px; text-align: left; }
        table.detail td { border: 1px solid #e5e7eb; padding: 5px; }
        .badge { font-weight: bold; }
    </style>
</head>
<body>
    <h1>Grade Book</h1>
    <div class="muted">
        Generated by {{ $context['generated_by'] ?? '-' }} at {{ $context['generated_at'] ?? now()->format('d M Y H:i') }}
    </div>

    <table class="summary">
        <tr>
            <td>Total Students <strong>{{ number_format($statistics['total_students']) }}</strong></td>
            <td>Graded <strong>{{ number_format($statistics['graded_count']) }}</strong></td>
            <td>Finalized <strong>{{ number_format($statistics['finalized_count']) }}</strong></td>
            <td>Average <strong>{{ $statistics['average_score'] ?? '-' }}</strong></td>
            <td>Median <strong>{{ $statistics['median_score'] ?? '-' }}</strong></td>
            <td>Pass Rate <strong>{{ $statistics['pass_rate'] }}%</strong></td>
        </tr>
    </table>

    <table class="detail">
        <thead>
            <tr>
                <th>NIM</th>
                <th>Mahasiswa</th>
                <th>Program Studi</th>
                <th>Mata Kuliah</th>
                <th>Kelas</th>
                <th>Tahun</th>
                <th>Semester</th>
                <th>Skor</th>
                <th>Nilai</th>
                <th>Point</th>
                <th>Lifecycle</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($rows as $row)
                <tr>
                    <td>{{ $row['nim'] }}</td>
                    <td>{{ $row['student_name'] }}</td>
                    <td>{{ $row['study_program'] }}</td>
                    <td>{{ $row['course'] }}</td>
                    <td>{{ $row['class'] }}</td>
                    <td>{{ $row['academic_year'] }}</td>
                    <td>{{ $row['semester_no'] }}</td>
                    <td>{{ $row['final_score'] !== null ? number_format($row['final_score'], 2) : '-' }}</td>
                    <td class="badge">{{ $row['letter_grade'] }}</td>
                    <td>{{ $row['grade_point'] !== null ? number_format($row['grade_point'], 2) : '-' }}</td>
                    <td>{{ $row['grade_status'] }}</td>
                    <td>{{ $row['result_status'] }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="12" style="text-align: center;">Tidak ada data.</td>
                </tr>
            @endforelse
        </tbody>
    </table>
</body>
</html>
