<?php

return [
    [
        'resource' => 'user',
        'plural' => 'users',
        'area' => 'access',
        'component' => 'admin.access.users',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'menu' => [
            'title' => 'Pengguna',
            'icon' => 'fas fa-users',
            'group' => 'Manajemen Akses',
            'group_order' => 80,
            'order' => 1,
        ],
    ],
    [
        'resource' => 'role',
        'plural' => 'roles',
        'area' => 'access',
        'component' => 'admin.access.roles',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'menu' => [
            'title' => 'Peran',
            'icon' => 'fas fa-user-shield',
            'group' => 'Manajemen Akses',
            'group_order' => 80,
            'order' => 2,
        ],
    ],
    [
        'resource' => 'permission',
        'plural' => 'permissions',
        'area' => 'access',
        'component' => 'admin.access.permissions',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'menu' => [
            'title' => 'Hak Akses',
            'icon' => 'fas fa-key',
            'group' => 'Manajemen Akses',
            'group_order' => 80,
            'order' => 3,
        ],
    ],
    [
        'resource' => 'setting',
        'plural' => 'settings',
        'area' => 'system',
        'component' => 'admin.system.settings',
        'actions' => ['index'],
        'menu' => [
            'title' => 'Pengaturan',
            'icon' => 'fas fa-cog',
            'group' => 'Sistem',
            'group_order' => 90,
            'order' => 1,
        ],
    ],
    [
        'resource' => 'menu',
        'plural' => 'menus',
        'area' => 'system',
        'component' => 'admin.system.menus',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'menu' => [
            'title' => 'Menu',
            'icon' => 'fas fa-bars',
            'group' => 'Sistem',
            'group_order' => 90,
            'order' => 2,
        ],
    ],
    [
        'resource' => 'activity-log',
        'plural' => 'activity-logs',
        'area' => 'system',
        'component' => 'admin.system.activity-logs',
        'actions' => ['index', 'show'],
        'menu' => [
            'title' => 'Log Aktivitas',
            'icon' => 'fas fa-history',
            'group' => 'Sistem',
            'group_order' => 90,
            'order' => 3,
        ],
    ],
    [
        'resource' => 'academic-year',
        'plural' => 'academic-years',
        'area' => 'academic',
        'component' => 'admin.academic.academic-years',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'menu' => [
            'title' => 'Tahun Akademik',
            'icon' => 'fas fa-calendar-alt',
            'group' => 'Akademik',
            'group_order' => 10,
            'order' => 1,
        ],
    ],
    [
        'resource' => 'faculty',
        'plural' => 'faculties',
        'area' => 'academic',
        'component' => 'admin.academic.faculties',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'menu' => [
            'title' => 'Fakultas',
            'icon' => 'fas fa-university',
            'group' => 'Akademik',
            'group_order' => 10,
            'order' => 2,
        ],
    ],
    [
        'resource' => 'study-program',
        'plural' => 'study-programs',
        'area' => 'academic',
        'component' => 'admin.academic.study-programs',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'menu' => [
            'title' => 'Program Studi',
            'icon' => 'fas fa-graduation-cap',
            'group' => 'Akademik',
            'group_order' => 10,
            'order' => 3,
        ],
    ],
    [
        'resource' => 'course',
        'plural' => 'courses',
        'area' => 'academic',
        'component' => 'admin.academic.courses',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'menu' => [
            'title' => 'Mata Kuliah',
            'icon' => 'fas fa-book',
            'group' => 'Akademik',
            'group_order' => 10,
            'order' => 4,
        ],
    ],
    [
        'resource' => 'curriculum',
        'plural' => 'curriculums',
        'area' => 'academic',
        'component' => 'admin.academic.curriculums',
        'actions' => ['index', 'create', 'edit', 'show'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Kurikulum',
            'icon' => 'fas fa-sitemap',
            'group' => 'Akademik',
            'group_order' => 10,
            'order' => 5,
        ],
    ],
    [
        'resource' => 'student-registration',
        'plural' => 'student-registrations',
        'area' => 'academic',
        'component' => 'admin.academic.student-registrations',
        'actions' => ['index', 'create', 'edit', 'show', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Registrasi Mahasiswa',
            'icon' => 'fas fa-file-alt',
            'group' => 'Akademik',
            'group_order' => 10,
            'order' => 6,
        ],
    ],
    [
        'resource' => 'academic-period',
        'plural' => 'academic-periods',
        'area' => 'academic',
        'component' => 'admin.academic.academic-periods',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'menu' => [
            'title' => 'Periode Akademik',
            'icon' => 'fas fa-clock',
            'group' => 'Akademik',
            'group_order' => 10,
            'order' => 7,
        ],
    ],
    [
        'resource' => 'course-offering',
        'plural' => 'course-offerings',
        'area' => 'academic',
        'component' => 'admin.academic.course-offerings',
        'actions' => ['index', 'create', 'edit', 'show', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Penawaran Kelas',
            'icon' => 'fas fa-list',
            'group' => 'Akademik',
            'group_order' => 10,
            'order' => 8,
        ],
    ],
    [
        'resource' => 'study-plan',
        'plural' => 'study-plans',
        'area' => 'academic',
        'component' => 'admin.academic.study-plans',
        'actions' => ['index', 'create', 'edit', 'show', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'KRS',
            'icon' => 'fas fa-clipboard-list',
            'group' => 'Akademik',
            'group_order' => 10,
            'order' => 9,
        ],
    ],
    [
        'resource' => 'course-schedule',
        'plural' => 'course-schedules',
        'area' => 'academic',
        'component' => 'admin.academic.course-schedules',
        'actions' => ['index', 'create', 'edit', 'show', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Jadwal Kuliah',
            'icon' => 'fas fa-calendar-days',
            'group' => 'Akademik',
            'group_order' => 10,
            'order' => 10,
        ],
    ],
    [
        'resource' => 'student-grade',
        'plural' => 'student-grades',
        'area' => 'academic',
        'component' => 'admin.academic.student-grades',
        'actions' => ['index', 'create', 'edit', 'show', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Nilai Mahasiswa',
            'icon' => 'fas fa-graduation-cap',
            'group' => 'Akademik',
            'group_order' => 10,
            'order' => 11,
        ],
    ],
    [
        'resource' => 'transcript',
        'plural' => 'transcripts',
        'area' => 'academic',
        'component' => 'admin.academic.transcripts',
        'actions' => ['index', 'show'],
        'permissions' => ['viewAny', 'view', 'update'],
        'menu' => [
            'title' => 'Transkrip',
            'icon' => 'fas fa-file-lines',
            'group' => 'Akademik',
            'group_order' => 10,
            'order' => 12,
        ],
    ],
    [
        'resource' => 'academic-advisor-assignment',
        'plural' => 'academic-advisor-assignments',
        'area' => 'academic',
        'component' => 'admin.academic.academic-advisor-assignments',
        'actions' => ['index', 'create', 'edit', 'show', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Dosen Wali',
            'icon' => 'fas fa-user-graduate',
            'group' => 'Akademik',
            'group_order' => 10,
            'order' => 13,
        ],
    ],
    [
        'resource' => 'building',
        'plural' => 'buildings',
        'area' => 'campus',
        'component' => 'admin.campus.buildings',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'menu' => [
            'title' => 'Gedung',
            'icon' => 'fas fa-building',
            'group' => 'Kampus',
            'group_order' => 60,
            'order' => 1,
        ],
    ],
    [
        'resource' => 'room',
        'plural' => 'rooms',
        'area' => 'campus',
        'component' => 'admin.campus.rooms',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'menu' => [
            'title' => 'Ruangan',
            'icon' => 'fas fa-door-open',
            'group' => 'Kampus',
            'group_order' => 60,
            'order' => 2,
        ],
    ],
    [
        'resource' => 'user-development-record',
        'plural' => 'user-development-records',
        'area' => 'organization',
        'component' => 'admin.organization.user-development-records',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Sertifikasi & Pelatihan',
            'icon' => 'fas fa-certificate',
            'group' => 'Kepegawaian',
            'group_icon' => 'fas fa-building-user',
            'group_order' => 35,
            'order' => 20,
        ],
    ],
    [
        'resource' => 'tridharma-record',
        'plural' => 'tridharma-records',
        'area' => 'organization',
        'component' => 'admin.organization.tridharma-records',
        'actions' => ['index', 'create', 'edit', 'show', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view', 'verify', 'approve', 'complete'],
        'menu' => [
            'title' => 'Tridharma',
            'icon' => 'fas fa-flask',
            'group' => 'Kepegawaian',
            'group_icon' => 'fas fa-building-user',
            'group_order' => 35,
            'order' => 21,
        ],
    ],
    [
        'resource' => 'lecturer-workload-period',
        'plural' => 'lecturer-workload-periods',
        'area' => 'organization',
        'component' => 'admin.organization.lecturer-workload-periods',
        'actions' => ['index', 'create', 'edit', 'show', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Periode BKD',
            'icon' => 'fas fa-calendar-days',
            'group' => 'Kepegawaian',
            'group_icon' => 'fas fa-building-user',
            'group_order' => 35,
            'order' => 22,
        ],
    ],
    [
        'resource' => 'lecturer-workload-rule',
        'plural' => 'lecturer-workload-rules',
        'area' => 'organization',
        'component' => 'admin.organization.lecturer-workload-rules',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Aturan SKS BKD',
            'icon' => 'fas fa-scale-balanced',
            'group' => 'Kepegawaian',
            'group_icon' => 'fas fa-building-user',
            'group_order' => 35,
            'order' => 23,
        ],
    ],
    [
        'resource' => 'lecturer-workload-submission',
        'plural' => 'lecturer-workload-submissions',
        'area' => 'organization',
        'component' => 'admin.organization.lecturer-workload-submissions',
        'actions' => ['index', 'show'],
        'permissions' => ['viewAny', 'view', 'update'],
        'menu' => [
            'title' => 'Review BKD',
            'icon' => 'fas fa-clipboard-list',
            'group' => 'Kepegawaian',
            'group_icon' => 'fas fa-building-user',
            'group_order' => 35,
            'order' => 24,
        ],
    ],
    [
        'resource' => 'edom-period',
        'plural' => 'edom-periods',
        'area' => 'organization',
        'component' => 'admin.organization.edom-periods',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Periode EDOM',
            'icon' => 'fas fa-comments',
            'group' => 'Kepegawaian',
            'group_icon' => 'fas fa-building-user',
            'group_order' => 35,
            'order' => 25,
        ],
    ],
    [
        'resource' => 'edom-question',
        'plural' => 'edom-questions',
        'area' => 'organization',
        'component' => 'admin.organization.edom-questions',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Pertanyaan EDOM',
            'icon' => 'fas fa-list-check',
            'group' => 'Kepegawaian',
            'group_icon' => 'fas fa-building-user',
            'group_order' => 35,
            'order' => 26,
        ],
    ],
    [
        'resource' => 'lecturer-performance-review',
        'plural' => 'lecturer-performance-reviews',
        'area' => 'organization',
        'component' => 'admin.organization.lecturer-performance-reviews',
        'actions' => ['index', 'show'],
        'permissions' => ['viewAny', 'view', 'update'],
        'menu' => [
            'title' => 'Review Performa',
            'icon' => 'fas fa-chart-line',
            'group' => 'Kepegawaian',
            'group_icon' => 'fas fa-building-user',
            'group_order' => 35,
            'order' => 27,
        ],
    ],
    [
        'resource' => 'lecturer-performance-rubric',
        'plural' => 'lecturer-performance-rubrics',
        'area' => 'organization',
        'component' => 'admin.organization.lecturer-performance-rubrics',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Rubrik Performa',
            'icon' => 'fas fa-sliders',
            'group' => 'Kepegawaian',
            'group_icon' => 'fas fa-building-user',
            'group_order' => 35,
            'order' => 28,
        ],
    ],
    [
        'resource' => 'employee-profile',
        'plural' => 'employee-profiles',
        'area' => 'organization',
        'component' => 'admin.organization.employee-profiles',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Pegawai',
            'icon' => 'fas fa-id-badge',
            'group' => 'Kepegawaian',
            'group_icon' => 'fas fa-building-user',
            'group_order' => 35,
            'order' => 1,
        ],
    ],
    [
        'resource' => 'organizational-position',
        'plural' => 'organizational-positions',
        'area' => 'organization',
        'component' => 'admin.organization.organizational-positions',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Jabatan',
            'icon' => 'fas fa-user-tie',
            'group' => 'Kepegawaian',
            'group_icon' => 'fas fa-building-user',
            'group_order' => 35,
            'order' => 2,
        ],
    ],
    [
        'resource' => 'employee-position-assignment',
        'plural' => 'employee-position-assignments',
        'area' => 'organization',
        'component' => 'admin.organization.employee-position-assignments',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Penugasan Jabatan',
            'icon' => 'fas fa-people-arrows',
            'group' => 'Kepegawaian',
            'group_icon' => 'fas fa-building-user',
            'group_order' => 35,
            'order' => 3,
        ],
    ],
    [
        'resource' => 'work-unit',
        'plural' => 'work-units',
        'area' => 'organization',
        'component' => 'admin.organization.work-units',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Unit Kerja',
            'icon' => 'fas fa-sitemap',
            'group' => 'Kepegawaian',
            'group_icon' => 'fas fa-building-user',
            'group_order' => 35,
            'order' => 4,
        ],
    ],
    [
        'resource' => 'approval-template',
        'plural' => 'approval-templates',
        'area' => 'organization',
        'component' => 'admin.organization.approval-templates',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Template Approval',
            'icon' => 'fas fa-diagram-project',
            'group' => 'Kepegawaian',
            'group_icon' => 'fas fa-building-user',
            'group_order' => 35,
            'order' => 5,
        ],
    ],
    [
        'resource' => 'approval-request',
        'plural' => 'approval-requests',
        'area' => 'organization',
        'component' => 'admin.organization.approval-requests',
        'actions' => ['index', 'create', 'show'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Approval',
            'icon' => 'fas fa-clipboard-check',
            'group' => 'Kepegawaian',
            'group_icon' => 'fas fa-building-user',
            'group_order' => 35,
            'order' => 6,
        ],
    ],
    [
        'resource' => 'employee-leave-type',
        'plural' => 'employee-leave-types',
        'area' => 'organization',
        'component' => 'admin.organization.employee-leave-types',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Jenis Cuti Pegawai',
            'icon' => 'fas fa-calendar-check',
            'group' => 'Kepegawaian',
            'group_icon' => 'fas fa-building-user',
            'group_order' => 35,
            'order' => 7,
        ],
    ],
    [
        'resource' => 'employee-leave-request',
        'plural' => 'employee-leave-requests',
        'area' => 'organization',
        'component' => 'admin.organization.employee-leave-requests',
        'actions' => ['index', 'create', 'show'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Cuti Pegawai',
            'icon' => 'fas fa-calendar-minus',
            'group' => 'Kepegawaian',
            'group_icon' => 'fas fa-building-user',
            'group_order' => 35,
            'order' => 8,
        ],
    ],
    [
        'resource' => 'employee-attendance-record',
        'plural' => 'employee-attendance-records',
        'area' => 'organization',
        'component' => 'admin.organization.employee-attendance-records',
        'actions' => ['index', 'create', 'show', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Absensi Pegawai',
            'icon' => 'fas fa-user-clock',
            'group' => 'Kepegawaian',
            'group_icon' => 'fas fa-building-user',
            'group_order' => 35,
            'order' => 9,
        ],
    ],
    [
        'resource' => 'employee-attendance-location',
        'plural' => 'employee-attendance-locations',
        'area' => 'organization',
        'component' => 'admin.organization.employee-attendance-locations',
        'actions' => ['index', 'create', 'edit'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Lokasi Absensi',
            'icon' => 'fas fa-location-dot',
            'group' => 'Kepegawaian',
            'group_icon' => 'fas fa-building-user',
            'group_order' => 35,
            'order' => 10,
        ],
    ],
    [
        'resource' => 'employee-leave-balance',
        'plural' => 'employee-leave-balances',
        'area' => 'organization',
        'component' => 'admin.organization.employee-leave-balances',
        'actions' => ['index'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Saldo Cuti Pegawai',
            'icon' => 'fas fa-scale-balanced',
            'group' => 'Kepegawaian',
            'group_icon' => 'fas fa-building-user',
            'group_order' => 35,
            'order' => 11,
        ],
    ],
    [
        'resource' => 'announcement',
        'plural' => 'announcements',
        'area' => 'publication',
        'component' => 'admin.publication.announcements',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view', 'publish'],
        'menu' => [
            'title' => 'Pengumuman',
            'icon' => 'fas fa-bullhorn',
            'group' => 'Publikasi',
            'group_icon' => 'fas fa-newspaper',
            'group_order' => 50,
            'order' => 1,
        ],
    ],
    [
        'resource' => 'admission-period',
        'plural' => 'admission-periods',
        'area' => 'admission',
        'component' => 'admin.admission.admission-periods',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Periode PMB',
            'icon' => 'fas fa-calendar-check',
            'group' => 'Penerimaan Mahasiswa',
            'group_icon' => 'fas fa-user-plus',
            'group_order' => 20,
            'order' => 1,
        ],
    ],
    [
        'resource' => 'admission-application',
        'plural' => 'admission-applications',
        'area' => 'admission',
        'component' => 'admin.admission.admission-applications',
        'actions' => ['index', 'show', 'delete'],
        'permissions' => ['viewAny', 'view', 'update', 'delete'],
        'menu' => [
            'title' => 'Pendaftar',
            'icon' => 'fas fa-file-signature',
            'group' => 'Penerimaan Mahasiswa',
            'group_icon' => 'fas fa-user-plus',
            'group_order' => 20,
            'order' => 2,
        ],
    ],
    [
        'resource' => 'admission-exam-schedule',
        'plural' => 'admission-exam-schedules',
        'area' => 'admission',
        'component' => 'admin.admission.admission-exam-schedules',
        'actions' => ['index', 'create', 'edit', 'show', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Jadwal Ujian',
            'icon' => 'fas fa-calendar-days',
            'group' => 'Penerimaan Mahasiswa',
            'group_icon' => 'fas fa-user-plus',
            'group_order' => 20,
            'order' => 3,
        ],
    ],
    [
        'resource' => 'admission-quota',
        'plural' => 'admission-quotas',
        'area' => 'admission',
        'component' => 'admin.admission.admission-quotas',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Kuota',
            'icon' => 'fas fa-chart-pie',
            'group' => 'Penerimaan Mahasiswa',
            'group_icon' => 'fas fa-user-plus',
            'group_order' => 20,
            'order' => 4,
        ],
    ],
    [
        'resource' => 'admission-selection',
        'plural' => 'admission-selection',
        'area' => 'admission',
        'component' => 'admin.admission.admission-selection',
        'actions' => ['index'],
        'permissions' => ['viewAny', 'update'],
        'menu' => [
            'title' => 'Seleksi',
            'icon' => 'fas fa-ranking-star',
            'group' => 'Penerimaan Mahasiswa',
            'group_icon' => 'fas fa-user-plus',
            'group_order' => 20,
            'order' => 5,
        ],
    ],
    [
        'resource' => 'nim-generation-rule',
        'plural' => 'nim-generation-rules',
        'area' => 'admission',
        'component' => 'admin.admission.nim-generation-rules',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Aturan NIM',
            'icon' => 'fas fa-id-card',
            'group' => 'Penerimaan Mahasiswa',
            'group_icon' => 'fas fa-user-plus',
            'group_order' => 20,
            'order' => 6,
        ],
    ],
    [
        'resource' => 'financial-dashboard',
        'plural' => 'dashboard',
        'area' => 'financial',
        'component' => 'admin.financial.dashboard',
        'actions' => [],
        'permissions' => ['viewAny', 'view'],
        'menu' => [
            'title' => 'Dashboard',
            'icon' => 'fas fa-chart-pie',
            'group' => 'Keuangan',
            'group_icon' => 'fas fa-wallet',
            'group_order' => 30,
            'order' => 0,
        ],
    ],
    [
        'resource' => 'tuition-fee',
        'plural' => 'tuition-fees',
        'area' => 'financial',
        'component' => 'admin.financial.tuition-fees',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Tarif SPP/UKT',
            'icon' => 'fas fa-money-bill-wave',
            'group' => 'Keuangan',
            'group_icon' => 'fas fa-wallet',
            'group_order' => 30,
            'order' => 1,
        ],
    ],
    [
        'resource' => 'student-invoice',
        'plural' => 'student-invoices',
        'area' => 'financial',
        'component' => 'admin.financial.student-invoices',
        'actions' => ['index', 'create', 'edit', 'show', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Tagihan Mahasiswa',
            'icon' => 'fas fa-file-invoice-dollar',
            'group' => 'Keuangan',
            'group_icon' => 'fas fa-wallet',
            'group_order' => 30,
            'order' => 2,
        ],
    ],
    [
        'resource' => 'payment',
        'plural' => 'payments',
        'area' => 'financial',
        'component' => 'admin.financial.payments',
        'actions' => ['index', 'show'],
        'permissions' => ['viewAny', 'view', 'update'],
        'menu' => [
            'title' => 'Pembayaran',
            'icon' => 'fas fa-receipt',
            'group' => 'Keuangan',
            'group_icon' => 'fas fa-wallet',
            'group_order' => 30,
            'order' => 3,
        ],
    ],
    [
        'resource' => 'installment-request',
        'plural' => 'installment-requests',
        'area' => 'financial',
        'component' => 'admin.financial.installment-requests',
        'actions' => ['index', 'show'],
        'permissions' => ['viewAny', 'view', 'update'],
        'menu' => [
            'title' => 'Pengajuan Cicilan',
            'icon' => 'fas fa-calendar-check',
            'group' => 'Keuangan',
            'group_icon' => 'fas fa-wallet',
            'group_order' => 30,
            'order' => 4,
        ],
    ],
    [
        'resource' => 'financial-hold',
        'plural' => 'financial-holds',
        'area' => 'financial',
        'component' => 'admin.financial.financial-holds',
        'actions' => ['index', 'show'],
        'permissions' => ['viewAny', 'view', 'update'],
        'menu' => [
            'title' => 'Blokir Keuangan',
            'icon' => 'fas fa-lock',
            'group' => 'Keuangan',
            'group_icon' => 'fas fa-wallet',
            'group_order' => 30,
            'order' => 5,
        ],
    ],
    [
        'resource' => 'clearance-policy',
        'plural' => 'clearance-policies',
        'area' => 'financial',
        'component' => 'admin.financial.clearance-policies',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Aturan Clearance',
            'icon' => 'fas fa-shield-halved',
            'group' => 'Keuangan',
            'group_icon' => 'fas fa-wallet',
            'group_order' => 30,
            'order' => 6,
        ],
    ],
    [
        'resource' => 'invoice-schedule',
        'plural' => 'invoice-schedules',
        'area' => 'financial',
        'component' => 'admin.financial.invoice-schedules',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Jadwal Tagihan',
            'icon' => 'fas fa-clock',
            'group' => 'Keuangan',
            'group_icon' => 'fas fa-wallet',
            'group_order' => 30,
            'order' => 7,
        ],
    ],
    [
        'resource' => 'scholarship',
        'plural' => 'scholarships',
        'area' => 'financial',
        'component' => 'admin.financial.scholarships',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Beasiswa',
            'icon' => 'fas fa-graduation-cap',
            'group' => 'Keuangan',
            'group_icon' => 'fas fa-wallet',
            'group_order' => 30,
            'order' => 8,
        ],
    ],
    [
        'resource' => 'student-scholarship',
        'plural' => 'student-scholarships',
        'area' => 'financial',
        'component' => 'admin.financial.student-scholarships',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Beasiswa Mahasiswa',
            'icon' => 'fas fa-award',
            'group' => 'Keuangan',
            'group_icon' => 'fas fa-wallet',
            'group_order' => 30,
            'order' => 9,
        ],
    ],
    [
        'resource' => 'invoice-adjustment',
        'plural' => 'invoice-adjustments',
        'area' => 'financial',
        'component' => 'admin.financial.invoice-adjustments',
        'actions' => ['index'],
        'permissions' => ['viewAny', 'view'],
        'menu' => [
            'title' => 'Penyesuaian Tagihan',
            'icon' => 'fas fa-scale-balanced',
            'group' => 'Keuangan',
            'group_icon' => 'fas fa-wallet',
            'group_order' => 30,
            'order' => 10,
        ],
    ],
    [
        'resource' => 'student-credit',
        'plural' => 'student-credits',
        'area' => 'financial',
        'component' => 'admin.financial.student-credits',
        'actions' => ['index'],
        'permissions' => ['viewAny', 'view'],
        'menu' => [
            'title' => 'Saldo Mahasiswa',
            'icon' => 'fas fa-coins',
            'group' => 'Keuangan',
            'group_icon' => 'fas fa-wallet',
            'group_order' => 30,
            'order' => 11,
        ],
    ],
    [
        'resource' => 'financial-report',
        'plural' => 'financial-reports',
        'area' => 'financial',
        'component' => 'admin.financial.financial-reports',
        'actions' => ['index'],
        'permissions' => ['viewAny', 'view'],
        'menu' => [
            'title' => 'Laporan',
            'icon' => 'fas fa-chart-line',
            'group' => 'Keuangan',
            'group_icon' => 'fas fa-wallet',
            'group_order' => 30,
            'order' => 12,
        ],
    ],
    [
        'resource' => 'student-service-dashboard',
        'plural' => 'dashboard',
        'area' => 'student-services',
        'component' => 'admin.student-services.dashboard',
        'actions' => [],
        'permissions' => ['viewAny', 'view'],
        'menu' => [
            'title' => 'Dashboard',
            'icon' => 'fas fa-chart-pie',
            'group' => 'Layanan Mahasiswa',
            'group_icon' => 'fas fa-hands-helping',
            'group_order' => 40,
            'order' => 0,
        ],
    ],
    [
        'resource' => 'service-letter-type',
        'plural' => 'service-letter-types',
        'area' => 'student-services',
        'component' => 'admin.student-services.letter-types',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Jenis Surat',
            'icon' => 'fas fa-file-signature',
            'group' => 'Layanan Mahasiswa',
            'group_icon' => 'fas fa-hands-helping',
            'group_order' => 40,
            'order' => 1,
        ],
    ],
    [
        'resource' => 'service-letter-request',
        'plural' => 'service-letter-requests',
        'area' => 'student-services',
        'component' => 'admin.student-services.letter-requests',
        'actions' => ['index', 'show'],
        'permissions' => ['viewAny', 'view', 'update'],
        'menu' => [
            'title' => 'Pengajuan Surat',
            'icon' => 'fas fa-envelope-open-text',
            'group' => 'Layanan Mahasiswa',
            'group_icon' => 'fas fa-hands-helping',
            'group_order' => 40,
            'order' => 2,
        ],
    ],
    [
        'resource' => 'leave-application',
        'plural' => 'leave-applications',
        'area' => 'student-services',
        'component' => 'admin.student-services.leave-applications',
        'actions' => ['index', 'show'],
        'permissions' => ['viewAny', 'view', 'update'],
        'menu' => [
            'title' => 'Pengajuan Cuti',
            'icon' => 'fas fa-calendar-minus',
            'group' => 'Layanan Mahasiswa',
            'group_icon' => 'fas fa-hands-helping',
            'group_order' => 40,
            'order' => 3,
        ],
    ],
    [
        'resource' => 'transfer-request',
        'plural' => 'transfer-requests',
        'area' => 'student-services',
        'component' => 'admin.student-services.transfer-requests',
        'actions' => ['index', 'show'],
        'permissions' => ['viewAny', 'view', 'update'],
        'menu' => [
            'title' => 'Pengajuan Pindah',
            'icon' => 'fas fa-right-left',
            'group' => 'Layanan Mahasiswa',
            'group_icon' => 'fas fa-hands-helping',
            'group_order' => 40,
            'order' => 4,
        ],
    ],
    [
        'resource' => 'graduation-batch',
        'plural' => 'graduation-batches',
        'area' => 'student-services',
        'component' => 'admin.student-services.graduation-batches',
        'actions' => ['index', 'create', 'edit', 'show'],
        'permissions' => ['viewAny', 'create', 'update', 'view'],
        'menu' => [
            'title' => 'Batch Yudisium',
            'icon' => 'fas fa-layer-group',
            'group' => 'Layanan Mahasiswa',
            'group_icon' => 'fas fa-hands-helping',
            'group_order' => 40,
            'order' => 5,
        ],
    ],
    [
        'resource' => 'graduation-application',
        'plural' => 'graduation-applications',
        'area' => 'student-services',
        'component' => 'admin.student-services.graduation-applications',
        'actions' => ['index', 'show'],
        'permissions' => ['viewAny', 'view', 'update'],
        'menu' => [
            'title' => 'Pengajuan Yudisium',
            'icon' => 'fas fa-user-graduate',
            'group' => 'Layanan Mahasiswa',
            'group_icon' => 'fas fa-hands-helping',
            'group_order' => 40,
            'order' => 6,
        ],
    ],
    [
        'resource' => 'graduation-policy',
        'plural' => 'graduation-policies',
        'area' => 'student-services',
        'component' => 'admin.student-services.graduation-policies',
        'actions' => ['index', 'create', 'edit'],
        'permissions' => ['viewAny', 'create', 'update', 'view'],
        'menu' => [
            'title' => 'Aturan Yudisium',
            'icon' => 'fas fa-user-check',
            'group' => 'Layanan Mahasiswa',
            'group_icon' => 'fas fa-hands-helping',
            'group_order' => 40,
            'order' => 7,
        ],
    ],
    [
        'resource' => 'graduation-document-requirement',
        'plural' => 'graduation-document-requirements',
        'area' => 'student-services',
        'component' => 'admin.student-services.graduation-document-requirements',
        'actions' => ['index', 'create', 'edit'],
        'permissions' => ['viewAny', 'create', 'update', 'view'],
        'menu' => [
            'title' => 'Dokumen Yudisium',
            'icon' => 'fas fa-folder-open',
            'group' => 'Layanan Mahasiswa',
            'group_icon' => 'fas fa-hands-helping',
            'group_order' => 40,
            'order' => 8,
        ],
    ],
    [
        'resource' => 'student-complaint-category',
        'plural' => 'student-complaint-categories',
        'area' => 'student-services',
        'component' => 'admin.student-services.complaint-categories',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Kategori Pengaduan',
            'icon' => 'fas fa-tags',
            'group' => 'Layanan Mahasiswa',
            'group_icon' => 'fas fa-hands-helping',
            'group_order' => 40,
            'order' => 9,
        ],
    ],
    [
        'resource' => 'student-complaint',
        'plural' => 'student-complaints',
        'area' => 'student-services',
        'component' => 'admin.student-services.complaints',
        'actions' => ['index', 'show'],
        'permissions' => ['viewAny', 'view', 'update', 'assign', 'respond', 'resolve'],
        'menu' => [
            'title' => 'Pengaduan',
            'icon' => 'fas fa-headset',
            'group' => 'Layanan Mahasiswa',
            'group_icon' => 'fas fa-hands-helping',
            'group_order' => 40,
            'order' => 10,
        ],
    ],

];
