<?php

return [
    [
        'resource' => 'user',
        'plural' => 'users',
        'area' => 'access',
        'component' => 'admin.access.users',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'menu' => [
            'title' => 'Users',
            'icon' => 'fas fa-users',
            'group' => 'Access Management',
            'order' => 1,
        ],
    ],
    [
        'resource' => 'role',
        'plural' => 'roles',
        'area' => 'access',
        'component' => 'admin.access.roles',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'menu' => [
            'title' => 'Roles',
            'icon' => 'fas fa-user-shield',
            'group' => 'Access Management',
            'order' => 2,
        ],
    ],
    [
        'resource' => 'permission',
        'plural' => 'permissions',
        'area' => 'access',
        'component' => 'admin.access.permissions',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'menu' => [
            'title' => 'Permissions',
            'icon' => 'fas fa-key',
            'group' => 'Access Management',
            'order' => 3,
        ],
    ],
    [
        'resource' => 'setting',
        'plural' => 'settings',
        'area' => 'system',
        'component' => 'admin.system.settings',
        'actions' => ['index'],
        'menu' => [
            'title' => 'Settings',
            'icon' => 'fas fa-cog',
            'group' => 'System',
            'order' => 1,
        ],
    ],
    [
        'resource' => 'menu',
        'plural' => 'menus',
        'area' => 'system',
        'component' => 'admin.system.menus',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'menu' => [
            'title' => 'Menus',
            'icon' => 'fas fa-bars',
            'group' => 'System',
            'order' => 2,
        ],
    ],
    [
        'resource' => 'activity-log',
        'plural' => 'activity-logs',
        'area' => 'system',
        'component' => 'admin.system.activity-logs',
        'actions' => ['index', 'show'],
        'menu' => [
            'title' => 'Activity Logs',
            'icon' => 'fas fa-history',
            'group' => 'System',
            'order' => 3,
        ],
    ],
    [
        'resource' => 'academic-year',
        'plural' => 'academic-years',
        'area' => 'academic',
        'component' => 'admin.academic.academic-years',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'menu' => [
            'title' => 'Academic Years',
            'icon' => 'fas fa-calendar-alt',
            'group' => 'Academic',
            'order' => 1,
        ],
    ],
    [
        'resource' => 'faculty',
        'plural' => 'faculties',
        'area' => 'academic',
        'component' => 'admin.academic.faculties',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'menu' => [
            'title' => 'Faculties',
            'icon' => 'fas fa-university',
            'group' => 'Academic',
            'order' => 2,
        ],
    ],
    [
        'resource' => 'study-program',
        'plural' => 'study-programs',
        'area' => 'academic',
        'component' => 'admin.academic.study-programs',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'menu' => [
            'title' => 'Study Programs',
            'icon' => 'fas fa-graduation-cap',
            'group' => 'Academic',
            'order' => 3,
        ],
    ],
    [
        'resource' => 'course',
        'plural' => 'courses',
        'area' => 'academic',
        'component' => 'admin.academic.courses',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'menu' => [
            'title' => 'Courses',
            'icon' => 'fas fa-book',
            'group' => 'Academic',
            'order' => 4,
        ],
    ],
    [
        'resource' => 'curriculum',
        'plural' => 'curriculums',
        'area' => 'academic',
        'component' => 'admin.academic.curriculums',
        'actions' => ['index', 'create', 'edit', 'show'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Curriculums',
            'icon' => 'fas fa-sitemap',
            'group' => 'Academic',
            'order' => 5,
        ],
    ],
    [
        'resource' => 'student-registration',
        'plural' => 'student-registrations',
        'area' => 'academic',
        'component' => 'admin.academic.student-registrations',
        'actions' => ['index', 'create', 'edit', 'show', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Student Registrations',
            'icon' => 'fas fa-file-alt',
            'group' => 'Academic',
            'order' => 6,
        ],
    ],
    [
        'resource' => 'academic-period',
        'plural' => 'academic-periods',
        'area' => 'academic',
        'component' => 'admin.academic.academic-periods',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'menu' => [
            'title' => 'Academic Periods',
            'icon' => 'fas fa-clock',
            'group' => 'Academic',
            'order' => 7,
        ],
    ],
    [
        'resource' => 'course-offering',
        'plural' => 'course-offerings',
        'area' => 'academic',
        'component' => 'admin.academic.course-offerings',
        'actions' => ['index', 'create', 'edit', 'show', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Course Offerings',
            'icon' => 'fas fa-list',
            'group' => 'Academic',
            'order' => 8,
        ],
    ],
    [
        'resource' => 'study-plan',
        'plural' => 'study-plans',
        'area' => 'academic',
        'component' => 'admin.academic.study-plans',
        'actions' => ['index', 'create', 'edit', 'show', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Study Plans',
            'icon' => 'fas fa-clipboard-list',
            'group' => 'Academic',
            'order' => 9,
        ],
    ],
    [
        'resource' => 'course-schedule',
        'plural' => 'course-schedules',
        'area' => 'academic',
        'component' => 'admin.academic.course-schedules',
        'actions' => ['index', 'create', 'edit', 'show', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Course Schedules',
            'icon' => 'fas fa-calendar-days',
            'group' => 'Academic',
            'order' => 10,
        ],
    ],
    [
        'resource' => 'student-grade',
        'plural' => 'student-grades',
        'area' => 'academic',
        'component' => 'admin.academic.student-grades',
        'actions' => ['index', 'create', 'edit', 'show', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Student Grades',
            'icon' => 'fas fa-graduation-cap',
            'group' => 'Academic',
            'order' => 11,
        ],
    ],
    [
        'resource' => 'transcript',
        'plural' => 'transcripts',
        'area' => 'academic',
        'component' => 'admin.academic.transcripts',
        'actions' => ['index', 'show'],
        'permissions' => ['viewAny', 'view', 'update'],
        'menu' => [
            'title' => 'Transcripts',
            'icon' => 'fas fa-file-lines',
            'group' => 'Academic',
            'order' => 12,
        ],
    ],
    [
        'resource' => 'academic-advisor-assignment',
        'plural' => 'academic-advisor-assignments',
        'area' => 'academic',
        'component' => 'admin.academic.academic-advisor-assignments',
        'actions' => ['index', 'create', 'edit', 'show', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Academic Advisor Assignments',
            'icon' => 'fas fa-user-graduate',
            'group' => 'Academic',
            'order' => 13,
        ],
    ],
    [
        'resource' => 'building',
        'plural' => 'buildings',
        'area' => 'campus',
        'component' => 'admin.campus.buildings',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'menu' => [
            'title' => 'Buildings',
            'icon' => 'fas fa-building',
            'group' => 'Campus',
            'order' => 1,
        ],
    ],
    [
        'resource' => 'room',
        'plural' => 'rooms',
        'area' => 'campus',
        'component' => 'admin.campus.rooms',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'menu' => [
            'title' => 'Rooms',
            'icon' => 'fas fa-door-open',
            'group' => 'Campus',
            'order' => 2,
        ],
    ],
    [
        'resource' => 'announcement',
        'plural' => 'announcements',
        'area' => 'publication',
        'component' => 'admin.publication.announcements',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view', 'publish'],
        'menu' => [
            'title' => 'Announcements',
            'icon' => 'fas fa-bullhorn',
            'group' => 'Publication',
            'group_icon' => 'fas fa-newspaper',
            'group_order' => 1,
            'order' => 1,
        ],
    ],
    [
        'resource' => 'admission-period',
        'plural' => 'admission-periods',
        'area' => 'admission',
        'component' => 'admin.admission.admission-periods',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Admission Periods',
            'icon' => 'fas fa-calendar-check',
            'group' => 'Admission',
            'group_icon' => 'fas fa-user-plus',
            'group_order' => 3,
            'order' => 1,
        ],
    ],
    [
        'resource' => 'admission-application',
        'plural' => 'admission-applications',
        'area' => 'admission',
        'component' => 'admin.admission.admission-applications',
        'actions' => ['index', 'show', 'delete'],
        'permissions' => ['viewAny', 'view', 'update', 'delete'],
        'menu' => [
            'title' => 'Applications',
            'icon' => 'fas fa-file-signature',
            'group' => 'Admission',
            'group_icon' => 'fas fa-user-plus',
            'group_order' => 3,
            'order' => 2,
        ],
    ],
    [
        'resource' => 'admission-exam-schedule',
        'plural' => 'admission-exam-schedules',
        'area' => 'admission',
        'component' => 'admin.admission.admission-exam-schedules',
        'actions' => ['index', 'create', 'edit', 'show', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Exam Schedules',
            'icon' => 'fas fa-calendar-days',
            'group' => 'Admission',
            'group_icon' => 'fas fa-user-plus',
            'group_order' => 3,
            'order' => 3,
        ],
    ],
    [
        'resource' => 'admission-quota',
        'plural' => 'admission-quotas',
        'area' => 'admission',
        'component' => 'admin.admission.admission-quotas',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Quotas',
            'icon' => 'fas fa-chart-pie',
            'group' => 'Admission',
            'group_icon' => 'fas fa-user-plus',
            'group_order' => 3,
            'order' => 4,
        ],
    ],
    [
        'resource' => 'admission-selection',
        'plural' => 'admission-selection',
        'area' => 'admission',
        'component' => 'admin.admission.admission-selection',
        'actions' => ['index'],
        'permissions' => ['viewAny', 'update'],
        'menu' => [
            'title' => 'Selection',
            'icon' => 'fas fa-ranking-star',
            'group' => 'Admission',
            'group_icon' => 'fas fa-user-plus',
            'group_order' => 3,
            'order' => 5,
        ],
    ],

];
