<?php

return [
    [
        'resource' => 'user',
        'plural' => 'users',
        'area' => 'access',
        'component' => 'admin.access.users',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'menu' => [
            'title' => 'Users',
            'icon' => 'fas fa-users',
            'group' => 'Access Management',
            'order' => 1,
        ],
    ],
    [
        'resource' => 'role',
        'plural' => 'roles',
        'area' => 'access',
        'component' => 'admin.access.roles',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'menu' => [
            'title' => 'Roles',
            'icon' => 'fas fa-user-shield',
            'group' => 'Access Management',
            'order' => 2,
        ],
    ],
    [
        'resource' => 'permission',
        'plural' => 'permissions',
        'area' => 'access',
        'component' => 'admin.access.permissions',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'menu' => [
            'title' => 'Permissions',
            'icon' => 'fas fa-key',
            'group' => 'Access Management',
            'order' => 3,
        ],
    ],
    [
        'resource' => 'setting',
        'plural' => 'settings',
        'area' => 'system',
        'component' => 'admin.system.settings',
        'actions' => ['index'],
        'menu' => [
            'title' => 'Settings',
            'icon' => 'fas fa-cog',
            'group' => 'System',
            'order' => 1,
        ],
    ],
    [
        'resource' => 'menu',
        'plural' => 'menus',
        'area' => 'system',
        'component' => 'admin.system.menus',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'menu' => [
            'title' => 'Menus',
            'icon' => 'fas fa-bars',
            'group' => 'System',
            'order' => 2,
        ],
    ],
    [
        'resource' => 'activity-log',
        'plural' => 'activity-logs',
        'area' => 'system',
        'component' => 'admin.system.activity-logs',
        'actions' => ['index', 'show'],
        'menu' => [
            'title' => 'Activity Logs',
            'icon' => 'fas fa-history',
            'group' => 'System',
            'order' => 3,
        ],
    ],
    [
        'resource' => 'academic-year',
        'plural' => 'academic-years',
        'area' => 'academic',
        'component' => 'admin.academic.academic-years',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'menu' => [
            'title' => 'Academic Years',
            'icon' => 'fas fa-calendar-alt',
            'group' => 'Academic',
            'order' => 1,
        ],
    ],
    [
        'resource' => 'faculty',
        'plural' => 'faculties',
        'area' => 'academic',
        'component' => 'admin.academic.faculties',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'menu' => [
            'title' => 'Faculties',
            'icon' => 'fas fa-university',
            'group' => 'Academic',
            'order' => 2,
        ],
    ],
    [
        'resource' => 'study-program',
        'plural' => 'study-programs',
        'area' => 'academic',
        'component' => 'admin.academic.study-programs',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'menu' => [
            'title' => 'Study Programs',
            'icon' => 'fas fa-graduation-cap',
            'group' => 'Academic',
            'order' => 3,
        ],
    ],
    [
        'resource' => 'course',
        'plural' => 'courses',
        'area' => 'academic',
        'component' => 'admin.academic.courses',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'menu' => [
            'title' => 'Courses',
            'icon' => 'fas fa-book',
            'group' => 'Academic',
            'order' => 4,
        ],
    ],
    [
        'resource' => 'curriculum',
        'plural' => 'curriculums',
        'area' => 'academic',
        'component' => 'admin.academic.curriculums',
        'actions' => ['index', 'create', 'edit', 'show'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Curriculums',
            'icon' => 'fas fa-sitemap',
            'group' => 'Academic',
            'order' => 5,
        ],
    ],
    [
        'resource' => 'student-registration',
        'plural' => 'student-registrations',
        'area' => 'academic',
        'component' => 'admin.academic.student-registrations',
        'actions' => ['index', 'create', 'edit', 'show', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Student Registrations',
            'icon' => 'fas fa-file-alt',
            'group' => 'Academic',
            'order' => 6,
        ],
    ],
    [
        'resource' => 'academic-period',
        'plural' => 'academic-periods',
        'area' => 'academic',
        'component' => 'admin.academic.academic-periods',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'menu' => [
            'title' => 'Academic Periods',
            'icon' => 'fas fa-clock',
            'group' => 'Academic',
            'order' => 7,
        ],
    ],
    [
        'resource' => 'course-offering',
        'plural' => 'course-offerings',
        'area' => 'academic',
        'component' => 'admin.academic.course-offerings',
        'actions' => ['index', 'create', 'edit', 'show', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Course Offerings',
            'icon' => 'fas fa-list',
            'group' => 'Academic',
            'order' => 8,
        ],
    ],
    [
        'resource' => 'study-plan',
        'plural' => 'study-plans',
        'area' => 'academic',
        'component' => 'admin.academic.study-plans',
        'actions' => ['index', 'create', 'edit', 'show', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Study Plans',
            'icon' => 'fas fa-clipboard-list',
            'group' => 'Academic',
            'order' => 9,
        ],
    ],
    [
        'resource' => 'course-schedule',
        'plural' => 'course-schedules',
        'area' => 'academic',
        'component' => 'admin.academic.course-schedules',
        'actions' => ['index', 'create', 'edit', 'show', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Course Schedules',
            'icon' => 'fas fa-calendar-days',
            'group' => 'Academic',
            'order' => 10,
        ],
    ],
    [
        'resource' => 'student-grade',
        'plural' => 'student-grades',
        'area' => 'academic',
        'component' => 'admin.academic.student-grades',
        'actions' => ['index', 'create', 'edit', 'show', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Student Grades',
            'icon' => 'fas fa-graduation-cap',
            'group' => 'Academic',
            'order' => 11,
        ],
    ],
    [
        'resource' => 'transcript',
        'plural' => 'transcripts',
        'area' => 'academic',
        'component' => 'admin.academic.transcripts',
        'actions' => ['index', 'show'],
        'permissions' => ['viewAny', 'view', 'update'],
        'menu' => [
            'title' => 'Transcripts',
            'icon' => 'fas fa-file-lines',
            'group' => 'Academic',
            'order' => 12,
        ],
    ],
    [
        'resource' => 'academic-advisor-assignment',
        'plural' => 'academic-advisor-assignments',
        'area' => 'academic',
        'component' => 'admin.academic.academic-advisor-assignments',
        'actions' => ['index', 'create', 'edit', 'show', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Academic Advisor Assignments',
            'icon' => 'fas fa-user-graduate',
            'group' => 'Academic',
            'order' => 13,
        ],
    ],
    [
        'resource' => 'building',
        'plural' => 'buildings',
        'area' => 'campus',
        'component' => 'admin.campus.buildings',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'menu' => [
            'title' => 'Buildings',
            'icon' => 'fas fa-building',
            'group' => 'Campus',
            'order' => 1,
        ],
    ],
    [
        'resource' => 'room',
        'plural' => 'rooms',
        'area' => 'campus',
        'component' => 'admin.campus.rooms',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'menu' => [
            'title' => 'Rooms',
            'icon' => 'fas fa-door-open',
            'group' => 'Campus',
            'order' => 2,
        ],
    ],
    [
        'resource' => 'announcement',
        'plural' => 'announcements',
        'area' => 'publication',
        'component' => 'admin.publication.announcements',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view', 'publish'],
        'menu' => [
            'title' => 'Announcements',
            'icon' => 'fas fa-bullhorn',
            'group' => 'Publication',
            'group_icon' => 'fas fa-newspaper',
            'group_order' => 1,
            'order' => 1,
        ],
    ],
    [
        'resource' => 'admission-period',
        'plural' => 'admission-periods',
        'area' => 'admission',
        'component' => 'admin.admission.admission-periods',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Admission Periods',
            'icon' => 'fas fa-calendar-check',
            'group' => 'Admission',
            'group_icon' => 'fas fa-user-plus',
            'group_order' => 3,
            'order' => 1,
        ],
    ],
    [
        'resource' => 'admission-application',
        'plural' => 'admission-applications',
        'area' => 'admission',
        'component' => 'admin.admission.admission-applications',
        'actions' => ['index', 'show', 'delete'],
        'permissions' => ['viewAny', 'view', 'update', 'delete'],
        'menu' => [
            'title' => 'Applications',
            'icon' => 'fas fa-file-signature',
            'group' => 'Admission',
            'group_icon' => 'fas fa-user-plus',
            'group_order' => 3,
            'order' => 2,
        ],
    ],
    [
        'resource' => 'admission-exam-schedule',
        'plural' => 'admission-exam-schedules',
        'area' => 'admission',
        'component' => 'admin.admission.admission-exam-schedules',
        'actions' => ['index', 'create', 'edit', 'show', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Exam Schedules',
            'icon' => 'fas fa-calendar-days',
            'group' => 'Admission',
            'group_icon' => 'fas fa-user-plus',
            'group_order' => 3,
            'order' => 3,
        ],
    ],
    [
        'resource' => 'admission-quota',
        'plural' => 'admission-quotas',
        'area' => 'admission',
        'component' => 'admin.admission.admission-quotas',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Quotas',
            'icon' => 'fas fa-chart-pie',
            'group' => 'Admission',
            'group_icon' => 'fas fa-user-plus',
            'group_order' => 3,
            'order' => 4,
        ],
    ],
    [
        'resource' => 'admission-selection',
        'plural' => 'admission-selection',
        'area' => 'admission',
        'component' => 'admin.admission.admission-selection',
        'actions' => ['index'],
        'permissions' => ['viewAny', 'update'],
        'menu' => [
            'title' => 'Selection',
            'icon' => 'fas fa-ranking-star',
            'group' => 'Admission',
            'group_icon' => 'fas fa-user-plus',
            'group_order' => 3,
            'order' => 5,
        ],
    ],
    [
        'resource' => 'nim-generation-rule',
        'plural' => 'nim-generation-rules',
        'area' => 'admission',
        'component' => 'admin.admission.nim-generation-rules',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'NIM Rules',
            'icon' => 'fas fa-id-card',
            'group' => 'Admission',
            'group_icon' => 'fas fa-user-plus',
            'group_order' => 3,
            'order' => 6,
        ],
    ],
    [
        'resource' => 'financial-dashboard',
        'plural' => 'dashboard',
        'area' => 'financial',
        'component' => 'admin.financial.dashboard',
        'actions' => [],
        'permissions' => ['viewAny', 'view'],
        'menu' => [
            'title' => 'Dashboard',
            'icon' => 'fas fa-chart-pie',
            'group' => 'Financial',
            'group_icon' => 'fas fa-wallet',
            'group_order' => 4,
            'order' => 0,
        ],
    ],
    [
        'resource' => 'tuition-fee',
        'plural' => 'tuition-fees',
        'area' => 'financial',
        'component' => 'admin.financial.tuition-fees',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Tuition Fees',
            'icon' => 'fas fa-money-bill-wave',
            'group' => 'Financial',
            'group_icon' => 'fas fa-wallet',
            'group_order' => 4,
            'order' => 1,
        ],
    ],
    [
        'resource' => 'student-invoice',
        'plural' => 'student-invoices',
        'area' => 'financial',
        'component' => 'admin.financial.student-invoices',
        'actions' => ['index', 'create', 'edit', 'show', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Student Invoices',
            'icon' => 'fas fa-file-invoice-dollar',
            'group' => 'Financial',
            'group_icon' => 'fas fa-wallet',
            'group_order' => 4,
            'order' => 2,
        ],
    ],
    [
        'resource' => 'payment',
        'plural' => 'payments',
        'area' => 'financial',
        'component' => 'admin.financial.payments',
        'actions' => ['index', 'show'],
        'permissions' => ['viewAny', 'view', 'update'],
        'menu' => [
            'title' => 'Payments',
            'icon' => 'fas fa-receipt',
            'group' => 'Financial',
            'group_icon' => 'fas fa-wallet',
            'group_order' => 4,
            'order' => 3,
        ],
    ],
    [
        'resource' => 'installment-request',
        'plural' => 'installment-requests',
        'area' => 'financial',
        'component' => 'admin.financial.installment-requests',
        'actions' => ['index', 'show'],
        'permissions' => ['viewAny', 'view', 'update'],
        'menu' => [
            'title' => 'Installment Requests',
            'icon' => 'fas fa-calendar-check',
            'group' => 'Financial',
            'group_icon' => 'fas fa-wallet',
            'group_order' => 4,
            'order' => 4,
        ],
    ],
    [
        'resource' => 'financial-hold',
        'plural' => 'financial-holds',
        'area' => 'financial',
        'component' => 'admin.financial.financial-holds',
        'actions' => ['index', 'show'],
        'permissions' => ['viewAny', 'view', 'update'],
        'menu' => [
            'title' => 'Financial Holds',
            'icon' => 'fas fa-lock',
            'group' => 'Financial',
            'group_icon' => 'fas fa-wallet',
            'group_order' => 4,
            'order' => 5,
        ],
    ],
    [
        'resource' => 'clearance-policy',
        'plural' => 'clearance-policies',
        'area' => 'financial',
        'component' => 'admin.financial.clearance-policies',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Clearance Policies',
            'icon' => 'fas fa-shield-halved',
            'group' => 'Financial',
            'group_icon' => 'fas fa-wallet',
            'group_order' => 4,
            'order' => 6,
        ],
    ],
    [
        'resource' => 'invoice-schedule',
        'plural' => 'invoice-schedules',
        'area' => 'financial',
        'component' => 'admin.financial.invoice-schedules',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Invoice Schedules',
            'icon' => 'fas fa-clock',
            'group' => 'Financial',
            'group_icon' => 'fas fa-wallet',
            'group_order' => 4,
            'order' => 7,
        ],
    ],
    [
        'resource' => 'scholarship',
        'plural' => 'scholarships',
        'area' => 'financial',
        'component' => 'admin.financial.scholarships',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Scholarships',
            'icon' => 'fas fa-graduation-cap',
            'group' => 'Financial',
            'group_icon' => 'fas fa-wallet',
            'group_order' => 4,
            'order' => 8,
        ],
    ],
    [
        'resource' => 'student-scholarship',
        'plural' => 'student-scholarships',
        'area' => 'financial',
        'component' => 'admin.financial.student-scholarships',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Student Scholarships',
            'icon' => 'fas fa-award',
            'group' => 'Financial',
            'group_icon' => 'fas fa-wallet',
            'group_order' => 4,
            'order' => 9,
        ],
    ],
    [
        'resource' => 'invoice-adjustment',
        'plural' => 'invoice-adjustments',
        'area' => 'financial',
        'component' => 'admin.financial.invoice-adjustments',
        'actions' => ['index'],
        'permissions' => ['viewAny', 'view'],
        'menu' => [
            'title' => 'Invoice Adjustments',
            'icon' => 'fas fa-scale-balanced',
            'group' => 'Financial',
            'group_icon' => 'fas fa-wallet',
            'group_order' => 4,
            'order' => 10,
        ],
    ],
    [
        'resource' => 'student-credit',
        'plural' => 'student-credits',
        'area' => 'financial',
        'component' => 'admin.financial.student-credits',
        'actions' => ['index'],
        'permissions' => ['viewAny', 'view'],
        'menu' => [
            'title' => 'Student Credits',
            'icon' => 'fas fa-coins',
            'group' => 'Financial',
            'group_icon' => 'fas fa-wallet',
            'group_order' => 4,
            'order' => 11,
        ],
    ],
    [
        'resource' => 'financial-report',
        'plural' => 'financial-reports',
        'area' => 'financial',
        'component' => 'admin.financial.financial-reports',
        'actions' => ['index'],
        'permissions' => ['viewAny', 'view'],
        'menu' => [
            'title' => 'Reports',
            'icon' => 'fas fa-chart-line',
            'group' => 'Financial',
            'group_icon' => 'fas fa-wallet',
            'group_order' => 4,
            'order' => 12,
        ],
    ],
    [
        'resource' => 'service-letter-type',
        'plural' => 'service-letter-types',
        'area' => 'student-services',
        'component' => 'admin.student-services.letter-types',
        'actions' => ['index', 'create', 'edit', 'delete'],
        'permissions' => ['viewAny', 'create', 'update', 'delete', 'view'],
        'menu' => [
            'title' => 'Letter Types',
            'icon' => 'fas fa-file-signature',
            'group' => 'Student Services',
            'group_icon' => 'fas fa-hands-helping',
            'group_order' => 5,
            'order' => 1,
        ],
    ],
    [
        'resource' => 'service-letter-request',
        'plural' => 'service-letter-requests',
        'area' => 'student-services',
        'component' => 'admin.student-services.letter-requests',
        'actions' => ['index', 'show'],
        'permissions' => ['viewAny', 'view', 'update'],
        'menu' => [
            'title' => 'Letter Requests',
            'icon' => 'fas fa-envelope-open-text',
            'group' => 'Student Services',
            'group_icon' => 'fas fa-hands-helping',
            'group_order' => 5,
            'order' => 2,
        ],
    ],
    [
        'resource' => 'leave-application',
        'plural' => 'leave-applications',
        'area' => 'student-services',
        'component' => 'admin.student-services.leave-applications',
        'actions' => ['index', 'show'],
        'permissions' => ['viewAny', 'view', 'update'],
        'menu' => [
            'title' => 'Leave Applications',
            'icon' => 'fas fa-calendar-minus',
            'group' => 'Student Services',
            'group_icon' => 'fas fa-hands-helping',
            'group_order' => 5,
            'order' => 3,
        ],
    ],

];
