<?php

use App\Http\Controllers\Academic\AssignmentFileController;
use App\Http\Controllers\Academic\AssignmentReportExportController;
use App\Http\Controllers\Academic\GradeAppealAttachmentController;
use App\Http\Controllers\Lecturer\CourseMaterialController;
use App\Http\Controllers\Lecturer\GradeBookExportController;
use App\Http\Controllers\Shared\Employee\TridharmaController;
use Illuminate\Support\Facades\Route;

Route::livewire('/announcements', 'lecturer.publication.announcements.index')->name('announcements.index');
Route::livewire('/announcements/create', 'lecturer.publication.announcements.create')->name('announcements.create');
Route::livewire('/announcements/{id}/edit', 'lecturer.publication.announcements.edit')->name('announcements.edit');
Route::livewire('/announcements/{id}', 'lecturer.publication.announcements.show')->name('announcements.show');
Route::livewire('/dashboard', 'lecturer.dashboard.index')->name('dashboard.index');
Route::livewire('/course-offerings', 'lecturer.course-offerings.index')->name('course-offerings.index');
Route::livewire('/calendar', 'lecturer.calendar.index')->name('calendar.index');
Route::livewire('/course-offerings/{id}', 'lecturer.course-offerings.show')->name('course-offerings.show');
Route::livewire('/course-offerings/{offeringId}/students', 'lecturer.course-offerings.students')->name('course-offerings.students');
Route::livewire('/course-offerings/{offeringId}/attendance', 'lecturer.course-offerings.attendance')->name('course-offerings.attendance');
Route::livewire('/course-offerings/{offeringId}/grades', 'lecturer.course-offerings.grades')->name('course-offerings.grades');
Route::livewire('/course-offerings/{offeringId}/materials', 'lecturer.course-materials.index')->name('course-materials.index');
Route::livewire('/course-materials', 'lecturer.course-materials.list')->name('course-materials.list');
Route::livewire('/course-materials/{material}', 'lecturer.course-materials.show')->name('course-materials.show');
Route::get('/course-materials/{id}/download', [CourseMaterialController::class, 'download'])->name('course-materials.download');
Route::get('/course-materials/{id}/preview/{fileId?}', [CourseMaterialController::class, 'preview'])->name('course-materials.preview');
Route::get('/course-materials/{id}/link/{fileId}', [CourseMaterialController::class, 'openLink'])->name('course-materials.link');
Route::livewire('/assignments', 'lecturer.assignments.index')->name('assignments.index');
Route::livewire('/course-offerings/{offeringId}/assignments/create', 'lecturer.assignments.create')->name('assignments.create');
Route::livewire('/assignments/{id}/edit', 'lecturer.assignments.edit')->name('assignments.edit');
Route::livewire('/assignments/{id}', 'lecturer.assignments.show')->name('assignments.show');
Route::livewire('/consultations', 'lecturer.consultations.index')->name('consultations.index');
Route::get('/assignments/instructions/{file}', [AssignmentFileController::class, 'lecturerInstruction'])->name('assignments.instructions.preview');
Route::get('/assignments/submissions/files/{file}', [AssignmentFileController::class, 'lecturerSubmission'])->name('assignments.submissions.files.preview');
Route::get('/assignments/{assignment}/report/csv', [AssignmentReportExportController::class, 'csv'])->name('assignments.report.csv');
Route::get('/assignments/{assignment}/report/xlsx', [AssignmentReportExportController::class, 'xlsx'])->name('assignments.report.xlsx');
Route::get('/assignments/{assignment}/report/pdf', [AssignmentReportExportController::class, 'pdf'])->name('assignments.report.pdf');
Route::livewire('/attendance-sessions/{sessionId}/edit', 'lecturer.attendance-sessions.edit')->name('attendance-sessions.edit');
Route::livewire('/student-grades', 'lecturer.student-grades.index')->name('student-grades.index');
Route::livewire('/student-grades/grade-book', 'lecturer.student-grades.grade-book')->name('student-grades.grade-book');
Route::livewire('/grade-appeals', 'lecturer.grade-appeals.index')->name('grade-appeals.index');
Route::get('/grade-appeal-attachments/{attachment}/preview', [GradeAppealAttachmentController::class, 'lecturerPreview'])->name('grade-appeal-attachments.preview');
Route::get('/student-grades/grade-book/export/csv', [GradeBookExportController::class, 'csv'])->name('student-grades.grade-book.export.csv');
Route::get('/student-grades/grade-book/export/xlsx', [GradeBookExportController::class, 'xlsx'])->name('student-grades.grade-book.export.xlsx');
Route::get('/student-grades/grade-book/export/pdf', [GradeBookExportController::class, 'pdf'])->name('student-grades.grade-book.export.pdf');
Route::livewire('/edom', 'lecturer.edom.index')->name('edom.index');
Route::livewire('/workloads', 'lecturer.workloads.index')->name('workloads.index');
Route::livewire('/workloads/{id}', 'lecturer.workloads.show')->name('workloads.show');
Route::livewire('/student-grades/{id}/edit', 'lecturer.student-grades.edit')->name('student-grades.edit');
Route::livewire('/academic-advising', 'lecturer.academic-advising.index')->name('academic-advising.index');
Route::livewire('/academic-advising/{assignmentId}', 'lecturer.academic-advising.show')->name('academic-advising.show');
Route::livewire('/students', 'lecturer.students.index')->name('students.index');
Route::get('/tridharma', [TridharmaController::class, 'index'])->name('tridharma.index');
Route::get('/tridharma/create', [TridharmaController::class, 'create'])->name('tridharma.create');
Route::post('/tridharma', [TridharmaController::class, 'store'])->name('tridharma.store');
Route::get('/tridharma/{record}', [TridharmaController::class, 'show'])->name('tridharma.show');
Route::post('/tridharma/{record}/submit', [TridharmaController::class, 'submitApproval'])->name('tridharma.submit');
Route::post('/tridharma/{record}/milestones', [TridharmaController::class, 'storeMilestone'])->name('tridharma.milestones.store');
Route::patch('/tridharma/{record}/milestones/{milestone}', [TridharmaController::class, 'updateMilestone'])->name('tridharma.milestones.update');
Route::post('/tridharma/{record}/outputs', [TridharmaController::class, 'storeOutput'])->name('tridharma.outputs.store');
Route::post('/tridharma/{record}/members', [TridharmaController::class, 'storeMember'])->name('tridharma.members.store');
Route::delete('/tridharma/{record}/members/{member}', [TridharmaController::class, 'destroyMember'])->name('tridharma.members.destroy');
Route::post('/tridharma/{record}/attachments', [TridharmaController::class, 'storeAttachment'])->name('tridharma.attachments.store');
Route::get('/users/search', [TridharmaController::class, 'searchUsers'])->name('users.search');
