<?php

use App\Http\Controllers\Academic\AssignmentFileController;
use App\Http\Controllers\Academic\GradeAppealAttachmentController;
use App\Http\Controllers\Financial\PaymentReceiptController;
use App\Http\Controllers\Lecturer\CourseMaterialController;
use App\Http\Controllers\StudentService\ComplaintAttachmentController;
use App\Http\Controllers\StudentService\GraduationDocumentController;
use App\Http\Controllers\StudentService\ServiceLetterDownloadController;
use Illuminate\Support\Facades\Route;

Route::livewire('/dashboard', 'student.dashboard.index')->name('dashboard.index');
Route::livewire('/registration', 'student.registration.index')->name('registration.index');
Route::livewire('/digital-id', 'student.digital-id.index')->name('digital-id.index');
Route::livewire('/study-plan', 'student.study-plan.index')->name('study-plan.index');
Route::livewire('/study-plan/comparison', 'student.study-plan.comparison')->name('study-plan.comparison');
Route::livewire('/progress', 'student.progress.index')->name('progress.index');
Route::livewire('/grades', 'student.grades.index')->name('grades.index');
Route::livewire('/grade-appeals', 'student.grade-appeals.index')->name('grade-appeals.index');
Route::get('/grade-appeal-attachments/{attachment}/preview', [GradeAppealAttachmentController::class, 'studentPreview'])->name('grade-appeal-attachments.preview');
Route::livewire('/financial/invoices', 'student.financial.invoices')->name('financial.invoices');
Route::livewire('/financial/invoices/{id}', 'student.financial.invoice-detail')->name('financial.invoices.show');
Route::get('/financial/payments/{payment}/receipt', [PaymentReceiptController::class, 'student'])->name('financial.payments.receipt');
Route::livewire('/transcript', 'student.transcript.index')->name('transcript.index');
Route::livewire('/schedule', 'student.schedule.index')->name('schedule.index');
Route::livewire('/schedule/{offeringId}/attendance', 'student.schedule.attendance.index')->name('schedule.attendance');
Route::livewire('/schedule/attendance/{sessionId}/record', 'student.schedule.attendance.record.index')->name('schedule.attendance.record');
Route::livewire('/materials', 'student.course-materials')->name('course-materials.index');
Route::livewire('/course-offerings/{offeringId}/materials', 'student.course-materials')->name('course-materials.offering');
Route::livewire('/learning/{material}', 'student.learning.show')->name('learning.show');
Route::livewire('/assignments', 'student.assignments.index')->name('assignments.index');
Route::livewire('/assignments/{id}', 'student.assignments.show')->name('assignments.show');
Route::livewire('/consultations', 'student.consultations.index')->name('consultations.index');
Route::get('/assignments/instructions/{file}', [AssignmentFileController::class, 'studentInstruction'])->name('assignments.instructions.preview');
Route::get('/assignments/submissions/files/{file}', [AssignmentFileController::class, 'studentSubmission'])->name('assignments.submissions.files.preview');
Route::get('/learning/{material}/preview/{fileId?}', [CourseMaterialController::class, 'preview'])->name('learning.preview');
Route::get('/learning/{material}/link/{fileId}', [CourseMaterialController::class, 'openLink'])->name('learning.link');
Route::get('/course-materials/{id}/download/{fileId}', [CourseMaterialController::class, 'download'])->name('course-materials.download');
Route::livewire('/announcements', 'student.publication.announcements.index')->name('announcements.index');
Route::livewire('/announcements/{id}', 'student.publication.announcements.show')->name('announcements.show');
Route::livewire('/edom', 'student.edom.index')->name('edom.index');
Route::livewire('/edom/{periodId}/{courseOfferingId}/{lecturerProfileId}', 'student.edom.show')->name('edom.show');
Route::livewire('/services/letters', 'student.student-services.letters')->name('student-services.letters');
Route::livewire('/services/letters/create', 'student.student-services.letter-create')->name('student-services.letters.create');
Route::livewire('/services/letters/{id}/edit', 'student.student-services.letter-edit')->name('student-services.letters.edit');
Route::livewire('/services/letters/{id}', 'student.student-services.letter-detail')->name('student-services.letters.show');
Route::get('/services/letters/{request}/download', [ServiceLetterDownloadController::class, 'student'])->name('student-services.letters.download');
Route::livewire('/services/leaves', 'student.student-services.leaves')->name('student-services.leaves');
Route::livewire('/services/leaves/create', 'student.student-services.leave-create')->name('student-services.leaves.create');
Route::livewire('/services/leaves/{id}/edit', 'student.student-services.leave-edit')->name('student-services.leaves.edit');
Route::livewire('/services/leaves/{id}', 'student.student-services.leave-detail')->name('student-services.leaves.show');
Route::livewire('/services/transfers', 'student.student-services.transfers')->name('student-services.transfers');
Route::livewire('/services/transfers/create', 'student.student-services.transfer-create')->name('student-services.transfers.create');
Route::livewire('/services/transfers/{id}/edit', 'student.student-services.transfer-edit')->name('student-services.transfers.edit');
Route::livewire('/services/transfers/{id}', 'student.student-services.transfer-detail')->name('student-services.transfers.show');
Route::livewire('/services/graduations', 'student.student-services.graduations')->name('student-services.graduations');
Route::livewire('/services/graduations/create', 'student.student-services.graduation-create')->name('student-services.graduations.create');
Route::livewire('/services/graduations/{id}/edit', 'student.student-services.graduation-edit')->name('student-services.graduations.edit');
Route::livewire('/services/graduations/{id}', 'student.student-services.graduation-detail')->name('student-services.graduations.show');
Route::get('/services/graduation-documents/{document}/preview', [GraduationDocumentController::class, 'studentPreview'])->name('student-services.graduation-documents.preview');
Route::livewire('/services/complaints', 'student.student-services.complaints')->name('student-services.complaints');
Route::livewire('/services/complaints/create', 'student.student-services.complaint-create')->name('student-services.complaints.create');
Route::livewire('/services/complaints/{id}', 'student.student-services.complaint-detail')->name('student-services.complaints.show');
Route::get('/services/complaint-attachments/{attachment}/download', [ComplaintAttachmentController::class, 'student'])->name('student-services.complaint-attachments.download');
