// Penerjemah ikon Font Awesome (dari DB menus / config/resources.php)
// ke lucide-react. Seluruh React WAJIB lucide — tidak ada Font Awesome.
import {
    ArrowRight,
    ArrowRightLeft,
    Award,
    Banknote,
    Bell,
    BookOpen,
    Briefcase,
    Building2,
    CalendarCheck,
    CalendarDays,
    CalendarMinus,
    ChartBar,
    ChartColumn,
    ChartLine,
    ChartPie,
    CircleDot,
    CircleQuestionMark,
    ClipboardCheck,
    ClipboardList,
    Clock,
    Cog,
    Coins,
    DoorOpen,
    FileDown,
    FileText,
    FlaskConical,
    FolderOpen,
    GraduationCap,
    HandHelping,
    Headset,
    History,
    House,
    IdCard,
    Images,
    Key,
    Layers,
    List,
    ListCheck,
    Lock,
    MailOpen,
    MapPin,
    Megaphone,
    Menu,
    MessagesSquare,
    Network,
    Newspaper,
    Presentation,
    Receipt,
    ReceiptText,
    Scale,
    Settings,
    Server,
    ShieldCheck,
    SlidersHorizontal,
    Star,
    Tags,
    University,
    UserCheck,
    UserCog,
    UserPlus,
    UserRound,
    UserShield,
    Users,
    Wallet,
    Wrench,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

const MAP: Record<string, LucideIcon> = {
    home: House,
    user: UserRound,
    users: Users,
    'user-shield': UserShield,
    'user-graduate': GraduationCap,
    'user-tie': Briefcase,
    'user-clock': UserRound,
    'user-check': UserCheck,
    'user-plus': UserPlus,
    'user-cog': UserCog,
    key: Key,
    cog: Cog,
    cogs: Settings,
    bars: Menu,
    history: History,
    bell: Bell,
    'calendar-alt': CalendarDays,
    'calendar-days': CalendarDays,
    'calendar-check': CalendarCheck,
    'calendar-minus': CalendarMinus,
    'calendar-star': Star,
    university: University,
    'graduation-cap': GraduationCap,
    book: BookOpen,
    sitemap: Network,
    'file-alt': FileText,
    'file-lines': FileText,
    clock: Clock,
    list: List,
    'clipboard-list': ClipboardList,
    'location-dot': MapPin,
    building: Building2,
    'door-open': DoorOpen,
    'boxes-packing': Layers,
    'screwdriver-wrench': Wrench,
    certificate: Award,
    flask: FlaskConical,
    'scale-balanced': Scale,
    comments: MessagesSquare,
    'list-check': ListCheck,
    'chart-line': ChartLine,
    'chart-bar': ChartBar,
    'chart-pie': ChartPie,
    'chart-column': ChartColumn,
    sliders: SlidersHorizontal,
    'id-badge': IdCard,
    'id-card': IdCard,
    'people-arrows': Users,
    'diagram-project': Network,
    'clipboard-check': ClipboardCheck,
    bullhorn: Megaphone,
    'circle-question': CircleQuestionMark,
    tags: Tags,
    newspaper: Newspaper,
    images: Images,
    'file-signature': FileText,
    'ranking-star': Award,
    'money-bill-wave': Banknote,
    'file-invoice-dollar': ReceiptText,
    receipt: Receipt,
    lock: Lock,
    'shield-halved': ShieldCheck,
    award: Award,
    coins: Coins,
    'envelope-open-text': MailOpen,
    'right-left': ArrowRightLeft,
    'layer-group': Layers,
    'folder-open': FolderOpen,
    headset: Headset,
    server: Server,
    wallet: Wallet,
    'hands-helping': HandHelping,
    'chalkboard-teacher': Presentation,
    'file-export': FileDown,
    'arrow-right': ArrowRight,
    briefcase: Briefcase,
};

export function faIconFor(faClass: string | null | undefined): LucideIcon {
    if (!faClass) return CircleDot;
    const key = faClass.replace(/^fas?\s+/, '').replace(/^fa-/, '').trim();
    return MAP[key] ?? CircleDot;
}

export function FaIcon({ name, size = 15 }: { name: string | null | undefined; size?: number }) {
    const Icon = faIconFor(name);
    return <Icon size={size} aria-hidden="true" />;
}
